 

export MPS_HOME=${RESOURCES_ARTIFACTS_MPS_DISTRIBUTION}
MPS_LIBS=`cat ${JOB_DIR}/${RESOURCES_MPS_JARS_LIST} |awk '{ORS=":"; print $1}'`
CLASSPATH=${MPS_LIBS}${RESOURCES_ARTIFACTS_MPS_SUPPORT_LIBS}/wildcard-1.03.jar:${RESOURCES_MPS_PATTERN_MATCHER}:${JOB_DIR}
#MODULE=NYoSh.sandbox
#CONCEPT=AlignerScript
#MODULE_GEN_CLASSES=`find ${JOB_DIR} -name classes_gen | awk '{ORS=":"; print $1}'`
#echo "MODULE_GEN_CLASSES: ${MODULE_GEN_CLASSES}"
MODEL=GobyWeb.sandbox
NYOSH_SCRIPTNAME=Aligner
CLASSNAME=${MODEL}.${NYOSH_SCRIPTNAME}
java -classpath ${CLASSPATH} ${CLASSNAME} "$@"

