#!/bin/bash
# Execute the samtools executable from the artifact repository:
expose_artifact_environment_variables
export GROOVY_HOME=${RESOURCES_ARTIFACTS_GROOVY_DISTRIBUTION}
${RESOURCES_ARTIFACTS_GROOVY_DISTRIBUTION}/bin/groovy "$@"