 

export MPS_HOME=${RESOURCES_ARTIFACTS_MPS_DISTRIBUTION}
MPS_LIBS=`cat ${RESOURCES_MPS_JARS_LIST} |awk '{ORS=":"; print $1}'`
NYOSH_SUPPORT_LIBS="$RESOURCES_ARTIFACTS_MPS_SUPPORT_LIBS/*"
CLASSPATH=${MPS_LIBS}${NYOSH_SUPPORT_LIBS}:${JOB_DIR}
MODEL=DeployableGobyWebPlugins
NYOSH_SCRIPTNAME=ResourceHomeScript
CLASSNAME=${MODEL}.${NYOSH_SCRIPTNAME}
java -classpath ${CLASSPATH} ${CLASSNAME} "$@"

